// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpSdpTrriIvmXnGf-AtwhJsnSZVkFplXU',
    appId: '1:131967677245:web:a246a7ca9e1ee489abcb54',
    messagingSenderId: '131967677245',
    projectId: 'zestix-94629',
    authDomain: 'zestix-94629.firebaseapp.com',
    storageBucket: 'zestix-94629.firebasestorage.app',
    measurementId: 'G-9QEE677FVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjHY6BxwxKdmIdFh1vkKN3TdmIZuvExwA',
    appId: '1:131967677245:android:c92da4ceaa0f1696abcb54',
    messagingSenderId: '131967677245',
    projectId: 'zestix-94629',
    storageBucket: 'zestix-94629.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAis6Jj3R-MTAhXnzFXz0mIMILNR1JZ5Nc',
    appId: '1:131967677245:ios:0eafa05636b5c6d4abcb54',
    messagingSenderId: '131967677245',
    projectId: 'zestix-94629',
    storageBucket: 'zestix-94629.firebasestorage.app',
    iosBundleId: 'com.example.safeVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAis6Jj3R-MTAhXnzFXz0mIMILNR1JZ5Nc',
    appId: '1:131967677245:ios:0eafa05636b5c6d4abcb54',
    messagingSenderId: '131967677245',
    projectId: 'zestix-94629',
    storageBucket: 'zestix-94629.firebasestorage.app',
    iosBundleId: 'com.example.safeVision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpSdpTrriIvmXnGf-AtwhJsnSZVkFplXU',
    appId: '1:131967677245:web:8ad82e9928597f36abcb54',
    messagingSenderId: '131967677245',
    projectId: 'zestix-94629',
    authDomain: 'zestix-94629.firebaseapp.com',
    storageBucket: 'zestix-94629.firebasestorage.app',
    measurementId: 'G-YPHNHTJCJN',
  );
}
